### PR TITLE
Add "3" Main Integration Tests

### LINKED ISSUE #48: Create three main integration tests
Fill out the input parameters completely, the LCM etc and test the entire functionality of the DECIDE-function.

### PR DESCRIPTION
**Pull request by K2017**
Closes #48

### CODE REVIEW

**Comment by elmaxe** [comment]
If I remember correctly, LIC 2 fails. It was like that before I added mine. Run yout tests before pushing plox ):

**Comment by K2017** [comment]
> 
> 
> If I remember correctly, LIC 2 fails. It was like that before I added mine. Run yout tests before pushing plox ):

Same when I pushed as well, this PR is designed to draw attention to this kind of thing

**Comment by andreaskth** [comment]
@elmaxe and @K2017 I assume you mean LIC1 and not LIC2? LIC1 had a bug where the requirement stated in the assignment pdf had been reversed (from "cannot be contained" to "can be contained"). That was one of the bugs I mentioned on slack that are now fixed (I changed the implementation and the unit test). If you can see which LIC it was that failed for you please let me know, because LIC2 is working for me.

**Comment by elmaxe** [comment]
Okey! Nice!

**Comment by andreaskth** [comment]
> Okey! Nice!

Nice as in "yeah it was LIC1 what wasn't working for me"? 😅  @elmaxe

**Comment by elmaxe** [comment]
Yes, I mixed index 1 and "the second" together

**Review by elmaxe — APPROVED** [review]

**Comment by andreaskth** [comment]
At the end I didn't comment out the "intermediate assertions" for the LIC:s etc. So in the strictest sense of "integration test" it may not qualify, but I strongly prefer it testing too much than too little (and that did catch more than one bug that was not found by our unit tests).

**Comment by K2017** [comment]
I would approve this, but Github won't let me because I created the PR, so please @andreaskth @Internet-Person-IP @teljoh could you take a look at this so we can be done with this?

**Review by Internet-Person-IP — APPROVED** [review]
ngl, did not look into it too much but looks alright.

**Pull request merged**
